name: Generate pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Python
        run: python generate.py
      - name: Push Results
        run: 
            git config --global user.name 'ted';
            git config --global user.email 'wattapik@users.noreply.github.com';
            if ! git diff --exit-code; then
                git add index.html;
                git commit -am "Update HTML";
                git push;
            fi
