on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: python generate.py
      - name: git
        run: 
          git config --local user.email "actions@github.com" 
          git config --local user.name actions-user
          
          if ! git diff --exit-code; then
              git add index.html
              git add rss
              git commit -am "GH Action Files added $(date)"
              git push -f origin main
          fi
