on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: python generate.py
      - name: git email
        run: git config --global user.email "actions@github.com" 
      - name: git name 
        run: git config --global user.name actions-user
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "update html and rss"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to master
        run: git push origin HEAD:main
